<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="All Test Suite" duration-ms="42047" started-at="2020-10-21T19:18:25Z" finished-at="2020-10-21T19:19:07Z">
    <groups>
    </groups>
    <test name="Main Login Tests" duration-ms="33911" started-at="2020-10-21T19:18:25Z" finished-at="2020-10-21T19:18:59Z">
      <class name="LinkedinMainLoginTests">
        <test-method status="PASS" signature="beforeMethod(java.lang.String)[pri:0, instance:LinkedinMainLoginTests@1cbbffcd]" name="beforeMethod" is-config="true" duration-ms="8011" started-at="2020-10-21T22:18:25Z" finished-at="2020-10-21T22:18:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="checkLinkedInSearchFunctionality(java.lang.String, java.lang.String)[pri:0, instance:LinkedinMainLoginTests@1cbbffcd]" name="checkLinkedInSearchFunctionality" duration-ms="14" started-at="2020-10-21T22:18:33Z" data-provider="validDataProvider" finished-at="2020-10-21T22:18:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[clarizenapi@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[MadjikMadjik123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login page is not loaded expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login page is not loaded expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at LinkedinMainLoginTests.checkLinkedInSearchFunctionality(LinkedinMainLoginTests.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkLinkedInSearchFunctionality -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:LinkedinMainLoginTests@1cbbffcd]" name="afterMethod" is-config="true" duration-ms="1187" started-at="2020-10-21T22:18:33Z" finished-at="2020-10-21T22:18:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=checkLinkedInSearchFunctionality status=FAILURE method=LinkedinMainLoginTests.checkLinkedInSearchFunctionality(java.lang.String, java.lang.String)[pri:0, instance:LinkedinMainLoginTests@1cbbffcd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.String)[pri:0, instance:LinkedinMainLoginTests@1cbbffcd]" name="beforeMethod" is-config="true" duration-ms="7161" started-at="2020-10-21T22:18:34Z" finished-at="2020-10-21T22:18:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="checkSuccessfulLoginToLinkedin(java.lang.String, java.lang.String)[pri:0, instance:LinkedinMainLoginTests@1cbbffcd]" name="checkSuccessfulLoginToLinkedin" duration-ms="17" started-at="2020-10-21T22:18:41Z" data-provider="validDataProvider" finished-at="2020-10-21T22:18:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[clarizenapi@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[MadjikMadjik123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login page is not loaded expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login page is not loaded expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at LinkedinMainLoginTests.checkSuccessfulLoginToLinkedin(LinkedinMainLoginTests.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkSuccessfulLoginToLinkedin -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:LinkedinMainLoginTests@1cbbffcd]" name="afterMethod" is-config="true" duration-ms="1159" started-at="2020-10-21T22:18:41Z" finished-at="2020-10-21T22:18:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=checkSuccessfulLoginToLinkedin status=FAILURE method=LinkedinMainLoginTests.checkSuccessfulLoginToLinkedin(java.lang.String, java.lang.String)[pri:0, instance:LinkedinMainLoginTests@1cbbffcd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.String)[pri:0, instance:LinkedinMainLoginTests@1cbbffcd]" name="beforeMethod" is-config="true" duration-ms="6917" started-at="2020-10-21T22:18:42Z" finished-at="2020-10-21T22:18:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="emptyUserEmailAndUserPasswordTest()[pri:0, instance:LinkedinMainLoginTests@1cbbffcd]" name="emptyUserEmailAndUserPasswordTest" duration-ms="13" started-at="2020-10-21T22:18:49Z" finished-at="2020-10-21T22:18:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login page is not loaded expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login page is not loaded expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at LinkedinMainLoginTests.emptyUserEmailAndUserPasswordTest(LinkedinMainLoginTests.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptyUserEmailAndUserPasswordTest -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:LinkedinMainLoginTests@1cbbffcd]" name="afterMethod" is-config="true" duration-ms="1159" started-at="2020-10-21T22:18:49Z" finished-at="2020-10-21T22:18:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=emptyUserEmailAndUserPasswordTest status=FAILURE method=LinkedinMainLoginTests.emptyUserEmailAndUserPasswordTest()[pri:0, instance:LinkedinMainLoginTests@1cbbffcd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.String)[pri:0, instance:LinkedinMainLoginTests@1cbbffcd]" name="beforeMethod" is-config="true" duration-ms="7093" started-at="2020-10-21T22:18:51Z" finished-at="2020-10-21T22:18:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="negativeLoginTest(java.lang.String, java.lang.String)[pri:0, instance:LinkedinMainLoginTests@1cbbffcd]" name="negativeLoginTest" duration-ms="10" started-at="2020-10-21T22:18:58Z" data-provider="notValidDataProvider" finished-at="2020-10-21T22:18:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[dasdsad12312@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[wrong12312312]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login page is not loaded expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login page is not loaded expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at LinkedinMainLoginTests.negativeLoginTest(LinkedinMainLoginTests.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeLoginTest -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:LinkedinMainLoginTests@1cbbffcd]" name="afterMethod" is-config="true" duration-ms="1146" started-at="2020-10-21T22:18:58Z" finished-at="2020-10-21T22:18:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=negativeLoginTest status=FAILURE method=LinkedinMainLoginTests.negativeLoginTest(java.lang.String, java.lang.String)[pri:0, instance:LinkedinMainLoginTests@1cbbffcd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- LinkedinMainLoginTests -->
    </test> <!-- Main Login Tests -->
    <test name="Search Tests" duration-ms="8089" started-at="2020-10-21T19:18:59Z" finished-at="2020-10-21T19:19:07Z">
      <class name="LinkedinSearchTest">
        <test-method status="PASS" signature="beforeMethod(java.lang.String)[pri:0, instance:LinkedinSearchTest@192d43ce]" name="beforeMethod" is-config="true" duration-ms="6924" started-at="2020-10-21T22:18:59Z" finished-at="2020-10-21T22:19:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="checkLinkedInSearchFunctionality()[pri:0, instance:LinkedinSearchTest@192d43ce]" name="checkLinkedInSearchFunctionality" duration-ms="11" started-at="2020-10-21T22:19:06Z" finished-at="2020-10-21T22:19:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login page is not loaded expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login page is not loaded expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at LinkedinSearchTest.checkLinkedInSearchFunctionality(LinkedinSearchTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkLinkedInSearchFunctionality -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:LinkedinSearchTest@192d43ce]" name="afterMethod" is-config="true" duration-ms="1152" started-at="2020-10-21T22:19:06Z" finished-at="2020-10-21T22:19:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=checkLinkedInSearchFunctionality status=FAILURE method=LinkedinSearchTest.checkLinkedInSearchFunctionality()[pri:0, instance:LinkedinSearchTest@192d43ce] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- LinkedinSearchTest -->
    </test> <!-- Search Tests -->
  </suite> <!-- All Test Suite -->
</testng-results>
